// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RailcarTrips.Database;

#nullable disable

namespace Database
{
    [DbContext(typeof(RailcarTripsContext))]
    [Migration("20260204051026_ProcessTripsFromEvents")]
    partial class ProcessTripsFromEvents
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("RailcarTrips.Database.Models.City", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnOrder(0);

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("TimeZone")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Cities");
                });

            modelBuilder.Entity("RailcarTrips.Database.Models.Equipment", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Equipment");
                });

            modelBuilder.Entity("RailcarTrips.Database.Models.EquipmentEvent", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("CityId")
                        .HasColumnType("bigint");

                    b.Property<string>("EquipmentId")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("EventCode")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)");

                    b.Property<DateTimeOffset>("EventTime")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("CityId");

                    b.HasIndex("EquipmentId");

                    b.ToTable("EquipmentEvents");
                });

            modelBuilder.Entity("RailcarTrips.Database.Models.Trip", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("DestinationCityId")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("EndUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("EquipmentId")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<long>("OriginCityId")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("StartUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<decimal>("TotalTripHours")
                        .HasColumnType("decimal(10, 2)");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "DestinationCityId" }, "IX_Trips_DestinationCityId");

                    b.HasIndex(new[] { "EquipmentId" }, "IX_Trips_EquipmentId");

                    b.HasIndex(new[] { "OriginCityId" }, "IX_Trips_OriginCityId");

                    b.HasIndex(new[] { "StartUtc" }, "IX_Trips_StartUtc")
                        .IsDescending();

                    b.ToTable("Trips");
                });

            modelBuilder.Entity("RailcarTrips.Database.Models.TripEvent", b =>
                {
                    b.Property<long>("TripId")
                        .HasColumnType("bigint");

                    b.Property<long>("EventId")
                        .HasColumnType("bigint");

                    b.Property<int>("EventSequence")
                        .HasColumnType("int");

                    b.HasKey("TripId", "EventId");

                    b.HasIndex("EventId");

                    b.HasIndex(new[] { "TripId", "EventSequence" }, "IX_TripEvents_TripId_Sequence");

                    b.ToTable("TripEvents");
                });

            modelBuilder.Entity("RailcarTrips.Database.Models.EquipmentEvent", b =>
                {
                    b.HasOne("RailcarTrips.Database.Models.City", "City")
                        .WithMany("Events")
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RailcarTrips.Database.Models.Equipment", "Equipment")
                        .WithMany("Events")
                        .HasForeignKey("EquipmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("City");

                    b.Navigation("Equipment");
                });

            modelBuilder.Entity("RailcarTrips.Database.Models.Trip", b =>
                {
                    b.HasOne("RailcarTrips.Database.Models.City", "DestinationCity")
                        .WithMany("DestinationTrips")
                        .HasForeignKey("DestinationCityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("RailcarTrips.Database.Models.Equipment", "Equipment")
                        .WithMany("Trips")
                        .HasForeignKey("EquipmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RailcarTrips.Database.Models.City", "OriginCity")
                        .WithMany("OriginTrips")
                        .HasForeignKey("OriginCityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("DestinationCity");

                    b.Navigation("Equipment");

                    b.Navigation("OriginCity");
                });

            modelBuilder.Entity("RailcarTrips.Database.Models.TripEvent", b =>
                {
                    b.HasOne("RailcarTrips.Database.Models.EquipmentEvent", "Event")
                        .WithMany()
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("RailcarTrips.Database.Models.Trip", "Trip")
                        .WithMany("TripEvents")
                        .HasForeignKey("TripId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Event");

                    b.Navigation("Trip");
                });

            modelBuilder.Entity("RailcarTrips.Database.Models.City", b =>
                {
                    b.Navigation("DestinationTrips");

                    b.Navigation("Events");

                    b.Navigation("OriginTrips");
                });

            modelBuilder.Entity("RailcarTrips.Database.Models.Equipment", b =>
                {
                    b.Navigation("Events");

                    b.Navigation("Trips");
                });

            modelBuilder.Entity("RailcarTrips.Database.Models.Trip", b =>
                {
                    b.Navigation("TripEvents");
                });
#pragma warning restore 612, 618
        }
    }
}
